export const SIGNUP_USER_REQUEST = "SIGNUP_USER_REQUEST";
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const SIGNUP_USER_FAILURE = "SIGNUP_USER_FAILURE";
export const SIGNUP_USER_SUCCESS_ERROR = "SIGNUP_USER_SUCCESS_ERROR"
export const ClEAR_SIGNUP_USER = "ClEAR_SIGNUP_USER"

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
export const LOGIN_USER_SUCCESS_ERROR = "LOGIN_USER_SUCCESS_ERROR"
export const ClEAR_LOGIN_USER = "ClEAR_LOGIN_USER"

export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAILURE = "LOGOUT_USER_FAILURE";
export const USER_LOGOUT = "USER_LOGOUT";


export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART"